In [10]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

import matplotlib.pyplot as plt

In [87]:
a = torch.ones(4, 3, 2, 1)
x = torch.rand(4, 3)
p = torch.ones(4)*.5

# p.unsqueeze(1)*torch.ones_like(x)
torch.max(x, p.unsqueeze(1))

tensor([[0.5000, 0.5000, 0.7932],
        [0.9841, 0.8066, 0.8366],
        [0.5000, 0.5000, 0.5860],
        [0.7507, 0.6960, 0.5000]])

In [90]:
.1e-3

0.0001

In [91]:
1e-4

0.0001

In [63]:
y = torch.rand(4)
y

tensor([0.7270, 0.8287, 0.2592, 0.9891])

In [64]:
torch.max(x, y)

tensor([0.7270, 0.8287, 0.4027, 0.9891])

In [34]:
a = np.ones([4, 3, 2, 1])
x = np.random.randn(4)

# np.tile(x, [3, 1])
x*a.T

array([[[[-0.35380292, -1.32268708, -1.87304219, -0.27905692],
         [-0.35380292, -1.32268708, -1.87304219, -0.27905692],
         [-0.35380292, -1.32268708, -1.87304219, -0.27905692]],

        [[-0.35380292, -1.32268708, -1.87304219, -0.27905692],
         [-0.35380292, -1.32268708, -1.87304219, -0.27905692],
         [-0.35380292, -1.32268708, -1.87304219, -0.27905692]]]])

In [35]:
a.T.shape

(1, 2, 3, 4)

In [26]:
class Model(nn.Module):
    def __init__(self, d, a=5):
        self.W = nn.Linear(d, a)
    
    def forward(self, X):
        X = self.W(X)
        return X
    
N = 1000
d = 16
a = 5

X_all = torch.rand(N, d)-.5
Y_all = torch.mm(X_all, torch.rand(d, a))

h = torch.rand(a)
Y_all = torch.mv(Y_all, h)
Y_all = (Y_all > 0).int()

batch_size = 32
ds = torch.utils.data.TensorDataset(X_all, Y_all)
dloader = torch.utils.data.DataLoader(ds, batch_size=32, shuffle=True)
num_epochs = 10
steps = N // batch_size

model = Model(d)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
loss_fn 
with tqdm(total=epochs*steps) as pbar:
    for X, Y in dloader:
        pbar.update(1)
        model(Y)